"""Inspect the original single nape panel within its misassigned head component."""
from pathlib import Path
import json,numpy as np,bpy
from mathutils import Vector
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'artifacts/dorsal_tv_r13';PACK=ROOT/'run/resourcepacks/eva_real_model/assets/projectseele';COMP=json.loads((OUT/'head_components.json').read_text())
bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False);scene=bpy.context.scene;scene.render.engine='CYCLES';scene.cycles.samples=12;scene.cycles.use_denoising=True;scene.render.resolution_x=900;scene.render.resolution_y=900;scene.render.resolution_percentage=100;scene.world.color=(.45,.45,.45)
bpy.ops.object.light_add(type='AREA',location=(-15,-60,225));lamp=bpy.context.object;lamp.data.energy=30000;lamp.data.size=80;lamp.rotation_euler=(Vector((0,-15,165))-lamp.location).to_track_quat('-Z','Y').to_euler()
bpy.ops.object.camera_add(location=(0,-100,245));camera=bpy.context.object;camera.rotation_euler=(Vector((0,-16,165))-camera.location).to_track_quat('-Z','Y').to_euler();camera.data.type='ORTHO';camera.data.ortho_scale=29;scene.camera=camera
for model in ['eva_unit00','eva_unit01','eva_unit02']:
 d=json.loads((ROOT/'artifacts/world_motion_r11/dorsal'/(model+'_uncut.mesh.json')).read_text());p=d['parts']['head'];a=np.array(p['vertices']).reshape(-1,3,8);a[:,:,:3]+=p['pivot'];ids=next(c['faces'] for c in COMP[model] if c['component']==5);v=a[ids].reshape(-1,8)
 mat=bpy.data.materials.new(model);mat.use_nodes=True;nodes=mat.node_tree.nodes;nodes.clear();tex=nodes.new('ShaderNodeTexImage');tex.image=bpy.data.images.load(str(PACK/'textures/entity'/(model+'.png')));shader=nodes.new('ShaderNodeBsdfPrincipled');out=nodes.new('ShaderNodeOutputMaterial');mat.node_tree.links.new(tex.outputs['Color'],shader.inputs['Base Color']);mat.node_tree.links.new(shader.outputs['BSDF'],out.inputs['Surface']);shader.inputs['Roughness'].default_value=.8
 mesh=bpy.data.meshes.new(model);mesh.from_pydata(v[:,[0,2,1]]*[1,-1,1],[],np.arange(len(v)).reshape(-1,3));mesh.update();uv=mesh.uv_layers.new();coords=v[:,3:5].copy();coords[:,1]=1-coords[:,1];uv.data.foreach_set('uv',coords.ravel());mesh.materials.append(mat);obj=bpy.data.objects.new(model,mesh);bpy.context.collection.objects.link(obj);scene.render.filepath=str(OUT/(model+'_nape_component.png'));bpy.ops.render.render(write_still=True);bpy.data.objects.remove(obj,do_unlink=True);bpy.data.meshes.remove(mesh)
