"""Private artist skin installation and technical UV normalization, no public redistribution."""
from pathlib import Path
from datetime import datetime
import json,shutil,hashlib,msvcrt
import numpy as np
from PIL import Image
from scipy.ndimage import distance_transform_edt

ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'artifacts/tv_facilities_r16';REF=OUT/'references';PACK=ROOT/'run/resourcepacks/eva_real_model/assets/projectseele';WORLD=ROOT/'run/saves/SEELE_TV_WORLD_PREVIEW_20260906'

def modern(im):
 if im.size==(64,64):return im.convert('RGBA')
 assert im.size==(64,32)
 # Mojang's legacy right-limb mirroring into the modern left-limb islands.
 out=Image.new('RGBA',(64,64));out.paste(im.convert('RGBA'),(0,0))
 for src,dst in [((4,16,8,20),(20,48)),((8,16,12,20),(24,48)),((0,20,4,32),(24,52)),((4,20,8,32),(20,52)),((8,20,12,32),(16,52)),((12,20,16,32),(28,52)),((44,16,48,20),(36,48)),((48,16,52,20),(40,48)),((40,20,44,32),(40,52)),((44,20,48,32),(36,52)),((48,20,52,32),(32,52)),((52,20,56,32),(44,52))]:
  out.paste(im.crop(src).transpose(Image.Transpose.FLIP_LEFT_RIGHT),dst)
 return out

def fuyutsuki():
 source=Path('C:/Users/liboy/.codex/generated_images/01a06f62-c70f-7b41-904c-d33fc1e86924/exec-a2d07e50-9ce5-4a00-b2cb-8cc781c8ef84.png')
 shutil.copy2(source,REF/'fuyutsuki_generated_atlas.png');im=Image.open(source).convert('RGBA');assert im.size==(1254,1254)
 out=Image.new('RGBA',(256,256));rows=[]
 def patch(src,dst):
  tile=np.array(im.crop(src));empty=tile[:,:,3]<245
  if empty.any():
   indices=distance_transform_edt(empty,return_distances=False,return_indices=True);tile[empty]=tile[tuple(indices[:,empty])]
  tile[:,:,3]=255;x,y,w,h=dst
  out.paste(Image.fromarray(tile).resize((w*4,h*4),Image.Resampling.LANCZOS),(x*4,y*4));rows.append(dict(source=src,uv=dst))
 for src,dst in [((218,12,393,170),(8,0,8,8)),((400,20,538,165),(16,0,8,8)),((67,176,213,357),(0,8,8,8)),((218,176,394,357),(8,8,8,8)),((401,176,547,357),(16,8,8,8)),((553,178,701,357),(24,8,8,8)),((466,384,638,448),(20,16,8,4)),((650,385,770,447),(28,16,8,4)),((350,456,458,738),(16,20,4,12)),((466,455,638,769),(20,20,8,12)),((649,456,771,738),(28,20,4,12)),((780,456,865,738),(32,20,8,12))]:patch(src,dst)
 for ox,oy in [(40,16),(32,48)]:
  for src,dst in [((66,399,156,465),(ox+4,oy,4,4)),((168,399,240,465),(ox+8,oy,4,4)),((31,474,61,769),(ox,oy+4,4,12)),((68,474,156,769),(ox+4,oy+4,4,12)),((166,474,240,769),(ox+8,oy+4,4,12)),((253,477,290,707),(ox+12,oy+4,4,12))]:patch(src,dst)
 for ox,oy in [(0,16),(16,48)]:
  for src,dst in [((67,805,155,891),(ox+4,oy,4,4)),((167,805,238,891),(ox+8,oy,4,4)),((32,905,61,1201),(ox,oy+4,4,12)),((67,906,155,1201),(ox+4,oy+4,4,12)),((167,906,239,1201),(ox+8,oy+4,4,12)),((252,907,369,1201),(ox+12,oy+4,4,12))]:patch(src,dst)
 target=ROOT/'src/main/resources/assets/projectseele/textures/entity/staff_fuyutsuki.png';out.save(target)
 (OUT/'fuyutsuki_uv_packing.json').write_text(json.dumps(dict(source=str(source),resolution=[256,256],method='Repack generated face islands into exact classic Minecraft UV rectangles; no inferred atlas coordinates at runtime',islands=rows),indent=2))
 return target

def main():
 fuyu=fuyutsuki();stamp=datetime.now().strftime('%Y%m%d_%H%M%S');backup=OUT/'skin_backup'/stamp;backup.mkdir(parents=True)
 dest=PACK/'textures/entity';dest.mkdir(parents=True,exist_ok=True);rows=[];catalog={}
 def install(key,file,author,page,slim=False):
  name='staff_online_'+key;src=REF/file;im=Image.open(src);original_size=im.size;im=modern(im);target=dest/(name+'.png')
  if target.exists():shutil.copy2(target,backup/target.name)
  im.save(target);rows.append(dict(name=key,author=author,page=page,downloaded_file=file,original_resolution=original_size,installed_resolution=im.size,sha256=hashlib.sha256(src.read_bytes()).hexdigest(),installed_sha256=hashlib.sha256(target.read_bytes()).hexdigest(),scope='Private local NPC resource pack'))
  return dict(texture='textures/entity/'+name+'.png',slim=slim)
 misato=install('misato','misatokatsuragi-evangelion.png','HeroGREEN (library uploader)','https://mcskins.top/skin/misatokatsuragi-evangelion')
 ritsuko=install('ritsuko','ritsuko_a.png','TarCoon☆CarToon','https://tarcoon.me/ritsuko-1/',True)
 maya=install('maya','maya_tarcoon.png','TarCoon☆CarToon','https://tarcoon.me/ritsuko-1/')
 medic=install('medic','medic_echo.png','EchoMatrix; credited bases M00NBEAM/JackForme','https://www.minecraftskins.com/skin/22473070/female-doctor/',True)
 uniforms=[install('un_'+str(i),'un_guard_'+str(i)+'.png','MCmilitarySkins','https://www.minecraftskins.com/skin/'+str(sid)+'/united-nations-peacekeeper-'+str(i)+'/') for i,sid in [(1,20980101),(2,20980174),(3,20981427)]]
 # Atlas assembly keeps the downloaded NERV uniform and actual separate
 # source head texels. Faces are not generated by upscaling the former skins.
 body=modern(Image.open(REF/'maya_tarcoon.png'))
 heads=[modern(Image.open(REF/n)) for n in ['un_guard_1.png','medic_echo.png','mechanic_mrz.png']]
 variants=[]
 for i,head in enumerate(heads):
  im=body.copy();im.paste(head.crop((0,0,32,16)),(0,0));im.paste(Image.new('RGBA',(32,16)),(32,0))
  if i==1:im.paste(head.crop((32,0,64,16)),(32,0))
  target=dest/f'staff_online_operator_{i}.png';im.save(target);variants.append(dict(texture='textures/entity/'+target.name,slim=False));rows.append(dict(name='operator_'+str(i),method='Unmodified UV island assembly: downloaded NERV uniform plus downloaded head',uniform='TarCoon Maya',head_source=['MCmilitarySkins UN1','EchoMatrix medic','MrZGaming mechanic'][i],resolution=[64,64],scope='Private local NPC resource pack'))
 catalog.update(misato=[misato],ritsuko=[ritsuko],maya=[maya],operator=variants,technician=variants,medic=[medic],guard=[variants[0]],un_guard=uniforms,un_crew=[uniforms[1],uniforms[2]],fuyutsuki=[dict(texture='textures/entity/staff_fuyutsuki.png',slim=False)])
 catalog['id:hyuga']=[variants[2]];catalog['id:aoba']=[variants[0]]
 folder=PACK/'staff';folder.mkdir(exist_ok=True);path=folder/'skins.json'
 if path.exists():shutil.copy2(path,backup/'skins.json')
 path.write_text(json.dumps(catalog,ensure_ascii=False,indent=2),encoding='utf8')
 (OUT/'staff_skin_sources.json').write_text(json.dumps(dict(installed=rows,generated_fuyutsuki=str(fuyu),unavailable_hd=['PMC maeci Misato/Ritsuko 128x128: browser view available, file export unavailable and HTTP403; not falsely claimed as installed']),ensure_ascii=False,indent=2),encoding='utf8')
 with (WORLD/'session.lock').open('r+b') as lock:
  msvcrt.locking(lock.fileno(),msvcrt.LK_NBLCK,1);path=WORLD/'nerv_staff_r15.json';shutil.copy2(path,backup/path.name);roster=json.loads(path.read_text(encoding='utf8'))
  if not any(s['id']=='fuyutsuki' for s in roster['stations']):
   from scan_regional_completion import volume,passable
   pos=(24,-389,349);a,q=volume((pos[0],pos[1]-1,pos[2]),(pos[0],pos[1]+1,pos[2]));states=[q[int(i)] for i in a[:,0,0]]
   assert not passable(states[0]) and passable(states[1]) and passable(states[2]),('Fuyutsuki post obstructed',states)
   roster['stations'].append(dict(id='fuyutsuki',name='冬月耕造',role='deputy',skin='fuyutsuki',feet=list(pos),yaw=180,room='commander_reception'))
  path.write_text(json.dumps(roster,ensure_ascii=False,indent=2),encoding='utf8')
 print('Artist skin catalog installed;',len(rows),'assets;',len(roster['stations']),'persistent posts. Fuyutsuki',fuyu)
if __name__=='__main__':main()
