package com.projectseele.registry;

import com.projectseele.ProjectSeele;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

/** All original synthesized audio (generated by tools/gen_sounds.ps1). */
public class ModSounds
{
    public static final DeferredRegister<SoundEvent> SOUNDS =
            DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, ProjectSeele.MODID);

    public static final RegistryObject<SoundEvent> ALARM = register("alarm");
    public static final RegistryObject<SoundEvent> BEAM_CHARGE = register("beam_charge");
    public static final RegistryObject<SoundEvent> BEAM_FIRE = register("beam_fire");
    public static final RegistryObject<SoundEvent> CROSS_EXPLOSION = register("cross_explosion");
    public static final RegistryObject<SoundEvent> CRYSTAL_HIT = register("crystal_hit");
    public static final RegistryObject<SoundEvent> CRYSTAL_BREAK = register("crystal_break");
    public static final RegistryObject<SoundEvent> DRILL = register("drill");
    public static final RegistryObject<SoundEvent> RAMIEL_HUM = register("ramiel_hum");
    public static final RegistryObject<SoundEvent> RIFLE_FIRE = register("rifle_fire");

    private static RegistryObject<SoundEvent> register(String name)
    {
        return SOUNDS.register(name,
                () -> SoundEvent.createVariableRangeEvent(new ResourceLocation(ProjectSeele.MODID, name)));
    }
}
